### ISSUE TITLE
Is this parser known to work? / Possibly broken file

### ISSUE THREAD

**Issue by ell1e** [abique/midi-parser#4]
I'm not fully understanding how to use it maybe. However, I tried basing it on the dump example, and my guesses were as follows: for every track, I'm supposed to get an `enum midi_parser_status` of `MIDI_PARSER_TRACK` once, followed by multiple times of `MIDI_PARSER_TRACK`/`MIDI_PARSER_TRACK_META`/`MIDI_PARSER_TRACK_SYSEX` until I reach the end of that particular track. Followed by all that again for every new track. So far, so good.

However, with the following midi file the header reports 14 tracks, but I only get 3 times `MIDI_PARSER_TRACK` before the end of file, and there are basically almost no note on/offs even though this is clearly a very busy song, and most events are just of status type "unknown" (as per `midi_status_name`). So something seems to be going wrong here. Or should I be doing something to extract note info from these unknown events? But how?

Here is the midi file: 
[test.mid.zip](https://github.com/abique/midi-parser/files/7212564/test.mid.zip)

**Comment by abique** [comment]
Hello,
This parser has some issues actually but I know what they are which is a good start!
The problems are that running status is not supported and real-time messages either.
I think it would require a bit of work to adjust the parser.
Regards,
Alex

**Comment by ell1e** [comment]
Will it be added? i love the simplicity of this parser, so it would be cool if it handled the common .midi files

**Comment by abique** [comment]
Yes I think it could :-)
I just need a little bit of time.
Alexandre Bique

**Comment by ell1e** [comment]
Very cool! Would be so nice if the attached file actually worked, so I can load up things like that. Looking forward to it.

**Comment by ell1e** [comment]
@abique I had some time so I tried to add it myself. See #5
